services:
  waha:
    image: devlikeapro/waha:2026.1.1
    container_name: wpp-bot
    ports:
      - "3000:3000"
    environment:
      WHATSAPP_DEFAULT_ENGINE: "GOWS"
      WAHA_API_KEY: ""
      WAHA_NO_API_KEY: "True"
      WAHA_DASHBOARD_PASSWORD: ""
      WAHA_DASHBOARD_NO_PASSWORD: "True"
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wpp-bot-api
    ports:
      - "5000:5000"